#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34003
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuickAction3DnetExample.Resource", IsApplication=true)]

namespace QuickAction3DnetExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::QuickAction3Dnet.Resource.Animation.disappear = global::QuickAction3DnetExample.Resource.Animation.disappear;
			global::QuickAction3Dnet.Resource.Animation.grow_from_bottom = global::QuickAction3DnetExample.Resource.Animation.grow_from_bottom;
			global::QuickAction3Dnet.Resource.Animation.grow_from_bottomleft_to_topright = global::QuickAction3DnetExample.Resource.Animation.grow_from_bottomleft_to_topright;
			global::QuickAction3Dnet.Resource.Animation.grow_from_bottomright_to_topleft = global::QuickAction3DnetExample.Resource.Animation.grow_from_bottomright_to_topleft;
			global::QuickAction3Dnet.Resource.Animation.grow_from_top = global::QuickAction3DnetExample.Resource.Animation.grow_from_top;
			global::QuickAction3Dnet.Resource.Animation.grow_from_topleft_to_bottomright = global::QuickAction3DnetExample.Resource.Animation.grow_from_topleft_to_bottomright;
			global::QuickAction3Dnet.Resource.Animation.grow_from_topright_to_bottomleft = global::QuickAction3DnetExample.Resource.Animation.grow_from_topright_to_bottomleft;
			global::QuickAction3Dnet.Resource.Animation.pump_bottom = global::QuickAction3DnetExample.Resource.Animation.pump_bottom;
			global::QuickAction3Dnet.Resource.Animation.pump_top = global::QuickAction3DnetExample.Resource.Animation.pump_top;
			global::QuickAction3Dnet.Resource.Animation.rail = global::QuickAction3DnetExample.Resource.Animation.rail;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_bottom = global::QuickAction3DnetExample.Resource.Animation.shrink_from_bottom;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_bottomleft_to_topright = global::QuickAction3DnetExample.Resource.Animation.shrink_from_bottomleft_to_topright;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_bottomright_to_topleft = global::QuickAction3DnetExample.Resource.Animation.shrink_from_bottomright_to_topleft;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_top = global::QuickAction3DnetExample.Resource.Animation.shrink_from_top;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_topleft_to_bottomright = global::QuickAction3DnetExample.Resource.Animation.shrink_from_topleft_to_bottomright;
			global::QuickAction3Dnet.Resource.Animation.shrink_from_topright_to_bottomleft = global::QuickAction3DnetExample.Resource.Animation.shrink_from_topright_to_bottomleft;
			global::QuickAction3Dnet.Resource.Drawable.action_item_btn = global::QuickAction3DnetExample.Resource.Drawable.action_item_btn;
			global::QuickAction3Dnet.Resource.Drawable.action_item_selected = global::QuickAction3DnetExample.Resource.Drawable.action_item_selected;
			global::QuickAction3Dnet.Resource.Drawable.arrow_down = global::QuickAction3DnetExample.Resource.Drawable.arrow_down;
			global::QuickAction3Dnet.Resource.Drawable.arrow_up = global::QuickAction3DnetExample.Resource.Drawable.arrow_up;
			global::QuickAction3Dnet.Resource.Drawable.popup = global::QuickAction3DnetExample.Resource.Drawable.popup;
			global::QuickAction3Dnet.Resource.Id.arrow_down = global::QuickAction3DnetExample.Resource.Id.arrow_down;
			global::QuickAction3Dnet.Resource.Id.arrow_up = global::QuickAction3DnetExample.Resource.Id.arrow_up;
			global::QuickAction3Dnet.Resource.Id.iv_icon = global::QuickAction3DnetExample.Resource.Id.iv_icon;
			global::QuickAction3Dnet.Resource.Id.scroller = global::QuickAction3DnetExample.Resource.Id.scroller;
			global::QuickAction3Dnet.Resource.Id.tracks = global::QuickAction3DnetExample.Resource.Id.tracks;
			global::QuickAction3Dnet.Resource.Id.tv_title = global::QuickAction3DnetExample.Resource.Id.tv_title;
			global::QuickAction3Dnet.Resource.Layout.action_item_horizontal = global::QuickAction3DnetExample.Resource.Layout.action_item_horizontal;
			global::QuickAction3Dnet.Resource.Layout.action_item_vertical = global::QuickAction3DnetExample.Resource.Layout.action_item_vertical;
			global::QuickAction3Dnet.Resource.Layout.horiz_separator = global::QuickAction3DnetExample.Resource.Layout.horiz_separator;
			global::QuickAction3Dnet.Resource.Layout.popup_horizontal = global::QuickAction3DnetExample.Resource.Layout.popup_horizontal;
			global::QuickAction3Dnet.Resource.Layout.popup_vertical = global::QuickAction3DnetExample.Resource.Layout.popup_vertical;
			global::QuickAction3Dnet.Resource.String.library_name = global::QuickAction3DnetExample.Resource.String.library_name;
			global::QuickAction3Dnet.Resource.Style.Animations = global::QuickAction3DnetExample.Resource.Style.Animations;
			global::QuickAction3Dnet.Resource.Style.Animations_PopDownMenu = global::QuickAction3DnetExample.Resource.Style.Animations_PopDownMenu;
			global::QuickAction3Dnet.Resource.Style.Animations_PopDownMenu_Center = global::QuickAction3DnetExample.Resource.Style.Animations_PopDownMenu_Center;
			global::QuickAction3Dnet.Resource.Style.Animations_PopDownMenu_Left = global::QuickAction3DnetExample.Resource.Style.Animations_PopDownMenu_Left;
			global::QuickAction3Dnet.Resource.Style.Animations_PopDownMenu_Reflect = global::QuickAction3DnetExample.Resource.Style.Animations_PopDownMenu_Reflect;
			global::QuickAction3Dnet.Resource.Style.Animations_PopDownMenu_Right = global::QuickAction3DnetExample.Resource.Style.Animations_PopDownMenu_Right;
			global::QuickAction3Dnet.Resource.Style.Animations_PopUpMenu = global::QuickAction3DnetExample.Resource.Style.Animations_PopUpMenu;
			global::QuickAction3Dnet.Resource.Style.Animations_PopUpMenu_Center = global::QuickAction3DnetExample.Resource.Style.Animations_PopUpMenu_Center;
			global::QuickAction3Dnet.Resource.Style.Animations_PopUpMenu_Left = global::QuickAction3DnetExample.Resource.Style.Animations_PopUpMenu_Left;
			global::QuickAction3Dnet.Resource.Style.Animations_PopUpMenu_Reflect = global::QuickAction3DnetExample.Resource.Style.Animations_PopUpMenu_Reflect;
			global::QuickAction3Dnet.Resource.Style.Animations_PopUpMenu_Right = global::QuickAction3DnetExample.Resource.Style.Animations_PopUpMenu_Right;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int disappear = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int grow_from_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int grow_from_bottomleft_to_topright = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int grow_from_bottomright_to_topleft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int grow_from_top = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int grow_from_topleft_to_bottomright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int grow_from_topright_to_bottomleft = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int pump_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int pump_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int rail = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int shrink_from_bottom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int shrink_from_bottomleft_to_topright = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int shrink_from_bottomright_to_topleft = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int shrink_from_top = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int shrink_from_topleft_to_bottomright = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int shrink_from_topright_to_bottomleft = 2130968591;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_item_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int action_item_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_down_arrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menu_eraser = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menu_info = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menu_ok = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu_search = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu_up_arrow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int popup = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int arrow_down = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int arrow_up = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int btn1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btn2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int btn3 = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int iv_icon = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int scroller = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tracks = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int tv_title = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_item_horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int action_item_vertical = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int horiz_separator = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int popup_horizontal = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int popup_vertical = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Animations = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Animations_PopDownMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Animations_PopDownMenu_Center = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Animations_PopDownMenu_Left = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int Animations_PopDownMenu_Reflect = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int Animations_PopDownMenu_Right = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Animations_PopUpMenu = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Animations_PopUpMenu_Center = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Animations_PopUpMenu_Left = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int Animations_PopUpMenu_Reflect = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int Animations_PopUpMenu_Right = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
