#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34003
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuickAction3Dnet.Resource", IsApplication=false)]

namespace QuickAction3Dnet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int disappear = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int grow_from_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int grow_from_bottomleft_to_topright = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int grow_from_bottomright_to_topleft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int grow_from_top = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int grow_from_topleft_to_bottomright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int grow_from_topright_to_bottomleft = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int pump_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int pump_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int rail = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int shrink_from_bottom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int shrink_from_bottomleft_to_topright = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int shrink_from_bottomright_to_topleft = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int shrink_from_top = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int shrink_from_topleft_to_bottomright = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public static int shrink_from_topright_to_bottomleft = 2130968591;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int action_item_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int action_item_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int arrow_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int arrow_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int popup = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public static int arrow_down = 2131165189;
			
			// aapt resource value: 0x7f070004
			public static int arrow_up = 2131165188;
			
			// aapt resource value: 0x7f070000
			public static int iv_icon = 2131165184;
			
			// aapt resource value: 0x7f070002
			public static int scroller = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int tracks = 2131165187;
			
			// aapt resource value: 0x7f070001
			public static int tv_title = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int action_item_horizontal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int action_item_vertical = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int horiz_separator = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int popup_horizontal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int popup_vertical = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int Animations = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int Animations_PopDownMenu = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int Animations_PopDownMenu_Center = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int Animations_PopDownMenu_Left = 2131099651;
			
			// aapt resource value: 0x7f060005
			public static int Animations_PopDownMenu_Reflect = 2131099653;
			
			// aapt resource value: 0x7f060004
			public static int Animations_PopDownMenu_Right = 2131099652;
			
			// aapt resource value: 0x7f060006
			public static int Animations_PopUpMenu = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int Animations_PopUpMenu_Center = 2131099655;
			
			// aapt resource value: 0x7f060008
			public static int Animations_PopUpMenu_Left = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public static int Animations_PopUpMenu_Reflect = 2131099658;
			
			// aapt resource value: 0x7f060009
			public static int Animations_PopUpMenu_Right = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
